--
-- GENERATED -- do not edit.
--
--   lua5.1 tools/make-selftest-vectors.lua
--
-- Every answer CeroSecSelfTest.vectors gives on lua5.1, which is the
-- canonical VM: what the engine is written to and what every bench in
-- tests/ runs on. CeroSecSelfTest.run() evaluates the same body on
-- whatever VM it finds itself on -- the game's Kahlua, in a real save --
-- and every line that differs is a line the game gets wrong.
--
-- tests/run.sh regenerates this into a temporary file and fails on a
-- diff, so a body with a line added or taken out is a red suite.
--

CeroSecSelfTest = CeroSecSelfTest or {}

CeroSecSelfTest.VECTORS = {
	{ name = "hexValue 7fffffff", want = "2147483647" },
	{ name = "hexValue 80000000", want = "2147483648" },
	{ name = "hexValue ffffffff", want = "4294967295" },
	{ name = "hexValue 00000000", want = "0" },
	{ name = "hexValue 0", want = "0" },
	{ name = "hexValue f", want = "15" },
	{ name = "hexValue deadbeef", want = "3735928559" },
	{ name = "hexValue DEADBEEF", want = "3735928559" },
	{ name = "hexValue empty", want = "nil" },
	{ name = "hexValue g", want = "nil" },
	{ name = "hexValue nil", want = "nil" },
	{ name = "hexValue number", want = "nil" },
	{ name = "digest empty 16", want = "1c016990080ede755131cf2f9b0ecd65" },
	{ name = "digest cerosec 16", want = "b97295d20703e3b16c92fe184fee28c9" },
	{ name = "digest long 16", want = "b9787ab05efbf82aedfa61a0cd3456b7" },
	{ name = "digest hi 0", want = "5e9988007e94e6b0e06e255777f56d3f" },
	{ name = "digest hi 4000", want = "705af4413c40728666b7ce8fdd92fc2c" },
	{ name = "digest 255 bytes", want = "abc1fa072053e9dd5bbbb0cf67c72aaa" },
	{ name = "hashPassword canonical", want = "$cs1$abcdef$74a662fe0a5af94dd93513930da000aa" },
	{ name = "hashPassword empty", want = "$cs1$abcdef$6867c2a95b184b9e76d37a1b86151354" },
	{ name = "hashPassword bad salt", want = "$cs1$0$135d271b5f8b41830eff4a992f54726f" },
	{ name = "derive root", want = "41620560d8a9a9a7368058a4d928336a" },
	{ name = "derive logh", want = "7d69b78bf872d631d685fc5b0cfc59e2" },
	{ name = "derive bad", want = "nil" },
	{ name = "key parts", want = "coffeeshop.logh.3" },
	{ name = "number logh 1", want = "8" },
	{ name = "number logm 1", want = "10" },
	{ name = "number logh 2", want = "8" },
	{ name = "number logm 2", want = "47" },
	{ name = "number logh 3", want = "5" },
	{ name = "number logm 3", want = "29" },
	{ name = "number logh 4", want = "5" },
	{ name = "number logm 4", want = "5" },
	{ name = "number logh 5", want = "5" },
	{ name = "number logm 5", want = "34" },
	{ name = "number logh 6", want = "5" },
	{ name = "number logm 6", want = "2" },
	{ name = "number n1", want = "1" },
	{ name = "number n100", want = "45" },
	{ name = "chance 50 root", want = "true" },
	{ name = "phoneKey 0 0", want = "2113" },
	{ name = "phoneKey 12 34", want = "2554" },
	{ name = "phoneKey 255 255", want = "8272" },
	{ name = "phoneKey bad", want = "nil" },
	{ name = "phoneText min 0", want = "200-0000" },
	{ name = "phoneText min 7", want = "200-0007" },
	{ name = "phoneText max last", want = "999-9999" },
	{ name = "phoneText out", want = "nil" },
	{ name = "format f", want = " 3.14" },
	{ name = "format f neg", want = "-0.50" },
	{ name = "format s left", want = "[ab      ]" },
	{ name = "format s right", want = "[      ab]" },
	{ name = "format 02d", want = "07" },
	{ name = "format 02d big", want = "123" },
	{ name = "format d zero", want = "0" },
	{ name = "format x", want = "ff" },
	{ name = "format percent", want = "50%" },
	{ name = "format two", want = "a:12" },
	{ name = "fmod 7 3", want = "1" },
	{ name = "fmod -7 3", want = "-1" },
	{ name = "fmod 7 -3", want = "1" },
	{ name = "fmod big", want = "15" },
	{ name = "mod 7 3", want = "1" },
	{ name = "CeroSecOS.mod 7 3", want = "1" },
	{ name = "CeroSecOS.mod big", want = "60828" },
	{ name = "CeroSecOS.mod exact 32", want = "65535" },
	{ name = "CeroSecOS.mod b zero", want = "nil" },
	{ name = "CeroSecOS.mod a neg", want = "nil" },
	{ name = "CeroSecOS.mod not number", want = "nil" },
	{ name = "floor -0.5", want = "-1" },
	{ name = "floor div", want = "-3" },
	{ name = "tostring int", want = "42" },
	{ name = "tostring div", want = "5" },
	{ name = "tostring neg zero", want = "0" },
	{ name = "byte of 0", want = "0" },
	{ name = "byte of 255", want = "255" },
	{ name = "len char 0", want = "3" },
	{ name = "byte middle", want = "65" },
	{ name = "rep 0", want = "[]" },
	{ name = "rep 3", want = "ababab" },
	{ name = "sub past end", want = "[bc]" },
	{ name = "sub negative", want = "def" },
	{ name = "upper", want = "ABC1" },
	{ name = "gsub count", want = "2" },
	{ name = "find plain", want = "2" },
	{ name = "concat", want = "a,b,c" },
	{ name = "concat numbers", want = "1-2-3" },
	{ name = "concat empty", want = "[]" },
	{ name = "timeFromParts start", want = "742208400" },
	{ name = "midnight", want = "742176000" },
	{ name = "formatStamp 1", want = "Jul  2 11:42" },
	{ name = "formatStamp 2", want = "Jul  3 11:42" },
	{ name = "formatStamp 3", want = "Jul  4 11:42" },
	{ name = "formatStamp zero", want = "Jan  1 00:00" },
	{ name = "formatDate start", want = "Fri Jul  9 09:00:00 1993" },
	{ name = "formatTime start", want = "1993-07-09 09:00:00 j=190 Fri Jul s=742208400 % %q" },
	{ name = "dateParts", want = "1993-7-9 9:0:0" },
	{ name = "dateParts of zero", want = "1970-1-1" },
	{ name = "truncate long", want = "abc~" },
	{ name = "truncate exact", want = "abcd" },
	{ name = "padRight", want = "[ab   ]" },
	{ name = "padLeft", want = "[   ab]" },
	{ name = "hasControlBytes no", want = "false" },
	{ name = "hasControlBytes yes", want = "true" },
	{ name = "parse ok", want = "true" },
	{ name = "parse missing done", want = "syntax error: missing 'done'" },
	{ name = "arith mod small", want = "1" },
	{ name = "arith mod big", want = "2" },
	{ name = "arith mod 32", want = "65535" },
	{ name = "arith neg div", want = "-3" },
	{ name = "arith neg mod", want = "-1" },
	{ name = "arith precedence", want = "5" },
	{ name = "arith argument", want = "2" },
	{ name = "arith argument count", want = "20" },
	{ name = "arith argument missing", want = "1" },
	{ name = "arith braces", want = "1" },
	{ name = "sync has disk", want = "true" },
	{ name = "sync has on", want = "true" },
	{ name = "sync has facing", want = "true" },
	{ name = "sync has v", want = "true" },
	{ name = "sync count", want = "4" },
	{ name = "sync has no seed", want = "false" },
	{ name = "sync has no os", want = "false" },
	{ name = "sync has no console", want = "false" },
	{ name = "saved has os", want = "true" },
	{ name = "saved has console", want = "true" },
	{ name = "saved has no disk", want = "false" },
	{ name = "saved has no seed", want = "false" },
	{ name = "saved count", want = "5" },
	{ name = "system saves seed", want = "true" },
	{ name = "system saves notes", want = "true" },
	{ name = "system count", want = "2" },
}
